### PR TITLE
Add support for a config file

### PR DESCRIPTION
**Pull request by meskio**
Now the configuration can be provided in a config file, in linux
~/.config/subs.[ini, yaml, toml, json]. As well as the existing SUBS_*
env variables.

Now is using dirs so it has support for paths in multiple platforms.

### CODE REVIEW

**Comment by meskio** [comment]
I'm kind of newbie in rust, I'm happy to hear what in my code is not rusty.

**Comment by xeals** [comment]
Thanks for contributing! Looks fairly good overall.

I was going to comment on the renaming of `Config` to `Conf`, but I now realise that this is written in a version that has crate-external namespacing issues. Porting to 2018 edition isn't a large task but would resolve that.

One thing I can point out that isn't just due to the refactor: since you've implemented a `Conf::new()`, the logic in `::config()` can be moved into it and calls to `::config()` refactored to use `Conf::new()`. The only code in there is sanity checking for the config values, after all.

If you want to fix the last point, I'm happy to wait before merging.

------

In terms of Rust-y-ness, my biggest comment is on error / unexpected value handling. There are many, many blog posts on this, but hopefully this is of some use anyway.

Use of `unwrap()` is unfortunately encouraged in some versions of the Rust Book and other guides; not sure if it's been shied away from in the 2018 edition or not. Using `unwrap()` is fine, but it's important to remember that handling an error is much preferred over panicking on one, even if it's just to panic with a clearer message.

Some of your uses, like on config/runtime directories are alright since we don't claim to support anything other than Linux (since we use Unix sockets), but note that they will return `None` on Unix systems that aren't Linux or MacOS (like a BSD). 

Generally I find that using `unwrap()` is fine to prototype, but moving something into permanent code (and I'm not throwing errors) I'll use `expect()` instead so that I can provide a reason *why* it matters that `unwrap`ping failed; e.g., https://github.com/xeals/subs/blob/83b279cffd54da4d8feef9e8318ec89a86ce30fe/src/player.rs#L135 or https://github.com/xeals/subs/blob/83b279cffd54da4d8feef9e8318ec89a86ce30fe/src/player.rs#L203-L206 I haven't been consistent in this program, but I've grown a bit since.

**Comment by meskio** [comment]
Updated, improved the unwrap with expects and added the config checks to the `Conf::new()`.

Thanks for the long explanation.

**Comment by xeals** [comment]
Looks good. Thanks again.

**Pull request merged**
